{
 "title": "Windows Exporter Dashboard",
 "description": "Windows Exporter Dashboard Created By Ismaeil Rasoulivand with love",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_cpu_time_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((windows_os_physical_memory_free_bytes{instance=~\"$server\"} / windows_os_total_visible_memory_size_bytes{instance=~\"$server\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{instance=\"$server\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Hard Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{instance=~\"$server\"} / windows_logical_disk_size_bytes{instance=~\"$server\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{instance=\"$server\",mode!=\"idle\"}[5m])) by (mode)) / 16)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$server\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$server\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent- Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{instance=~\"$server\"}[$interval]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received- Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Services by state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{instance=~\"$server\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_logical_disk_read_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent-Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received-Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Partitions Free Space",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}